export const itemProduct = [
  {
    id: 1,
    image: '/assets/people.svg',
    productName: "Color Item Type / satu",
    price: 39.99,
    discount: 19.99,
    description:"Kacamata tampan dan berani Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    size: ["small", "medium", "large"],
  },
  {
    id: 2,
    image: '/assets/people.svg',
    productName: "Color Item Type / dua",
    price: 39.99,
    discount: 19.99,
    description:"Kacamata tampan dan berani Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    size: ["small", "medium", "large"],
  },
  {
    id: 3,
    image: '/assets/people.svg',
    productName: "Color Item Type / tiga",
    price: 39.99,
    discount: 19.99,
    description:"Kacamata tampan dan berani Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    size: ["small", "medium", "large"],
  },
  {
    id: 4,
    image: '/assets/people.svg',
    productName: "Color Item Type / empat",
    price: 39.99,
    discount: 19.99,
    description:"Kacamata tampan dan berani Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    size: ["small", "medium", "large"],
  },
  {
    id: 5,
    image: '/assets/people.svg',
    productName: "Color Item Type / lima",
    price: 39.99,
    discount: 19.99,
    description:"Kacamata tampan dan berani Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    size: ["small", "medium", "large"],
  },
  {
    id: 6,
    image: '/assets/people.svg',
    productName: "Color Item Type / enam",
    price: 39.99,
    discount: 19.99,
    description:"Kacamata tampan dan berani Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    size: ["small", "medium", "large"],
  },
  {
    id: 7,
    image: '/assets/people.svg',
    productName: "Color Item Type / tujuh",
    price: 39.99,
    discount: 19.99,
    description:"Kacamata tampan dan berani Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    size: ["small", "medium", "large"],
  },
  {
    id: 8,
    image: '/assets/people.svg',
    productName: "Color Item Type / delapan",
    price: 39.99,
    discount: 19.99,
    description:"Kacamata tampan dan berani Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    size: ["small", "medium", "large"],
  },
  {
    id: 9,
    image: '/assets/people.svg',
    productName: "Color Item Type / sembilan",
    price: 39.99,
    discount: 19.99,
    description:"Kacamata tampan dan berani Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    size: ["small", "medium", "large"],
  },
];

export default itemProduct
