export const GET_PRODUCTS = "[PROODUCT] GET PRODUCTS";

export const GET_CARTS = "[CART] GET CARTS";
export const DELETE_CART_BY_ID = "[CART] DELETE CART BY ID";
export const ADD_QTY_BY_ID = "[CART] ADD QTY CART BY ID";
export const REMOVE_QTY_BY_ID = "[CART] REMOVE QTY CART BY ID";
